language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-telegram.gemspec
- gem install sensu-plugins-telegram-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: TgMN+aURCSc0ilnRDJpQ3ySfEriGppMn5onctJJWN6ghReaKe8faXjcB/RWljfIBQgxkijy2svMgN+y6cRyii6dTfnFnZY4yUO+u6+HU5QNzb5uVbn2MKU5KfpsQFYwToPSKbQ1YcvA39U67sS4aRVf0TsrPoQfXZxOeLytNtz8=
  gem: sensu-plugins-telegram
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-telegram
